################################
## Prometheus Ingress
#################################
{{- if .Values.global.baseDomain }}
{{- if .Values.global.openShift.useRouter }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    tier: prometheus-networking
    component: prometheus-ingress
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  host: {{ template "prometheus.url" . }}
  to:
    kind: Service
    name: "{{ .Release.Name }}-nginx"
    weight: 100
  wildcardPolicy: None
  {{- if or .Values.global.acme .Values.global.tlsSecret }}
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  {{- else }}
  port:
    targetPort: http
  {{- end }}
---
{{- end }}
kind: Ingress
apiVersion: {{ template "apiVersion.Ingress" . }}
metadata:
  name: {{ template "prometheus.fullname" . }}-ingress
  labels:
    tier: prometheus-networking
    component: prometheus-ingress
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Release.Name }}-nginx"
    kubernetes.io/tls-acme: {{ eq .Values.global.acme true | quote }}
    nginx.ingress.kubernetes.io/auth-url: https://houston.{{ .Values.global.baseDomain }}/v1/authorization
    nginx.ingress.kubernetes.io/auth-signin: https://app.{{ .Values.global.baseDomain }}/login
    nginx.ingress.kubernetes.io/auth-response-headers: authorization, username, email
{{- if .Values.global.openShift.useRouter }}
    haproxy.router.openshift.io/ip_whitelist: "127.0.0.1/32"
{{- end }}
spec:
  {{- if or .Values.global.tlsSecret .Values.global.acme }}
  tls:
  {{- if .Values.global.acme }}
    - secretName: prometheus-tls
  {{- end }}
  {{- if .Values.global.tlsSecret }}
    - secretName: {{ .Values.global.tlsSecret }}
  {{- end }}
      hosts:
        - {{ template "prometheus.url" . }}
  {{- end }}
  rules:
    - host: {{ template "prometheus.url" . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "prometheus.fullname" . }}
              servicePort: prometheus-data
{{- end }}
